<a href="https://colab.research.google.com/github/theagegeshidze/theagegeshidze.github.io/blob/main/Project_annualemissionsmap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arrays, vectors, `lists`  
Cell navigation: `Ctrl+Enter` runs the cell  
`Alt+Enter` runs and adds a new one below
`Shift+Etner` runs and steps into the next cell

In [ ]:
a = [2,4,3,"fdfd",[5,6]]

In [ ]:
a

[2, 4, 3, 'fdfd', [5, 6]]

In [ ]:
a[4][0]

5

This is a nice **comments**  
Dictionary, Object, Hash table

In [ ]:
b={'alfa':1,
'beta':27, 
'gamma':[0,1,2],
'delta':67.3,
'ninety-eight':{
    'a': 5, 
    'b':7}
   }

In [ ]:
b['ninety-eight']['a']

5

In [ ]:
b.keys(),b.values()

(dict_keys(['alfa', 'beta', 'gamma', 'delta', 'ninety-eight']),
 dict_values([1, 27, [0, 1, 2], 67.3, {'a': 5, 'b': 7}]))

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('worldemissions.csv')

In [ ]:
df

    Entity      Code  Year  Annual C02 emissions
0    World  OWID_WRL  1750               9350528
1    World  OWID_WRL  1751               9350528
2    World  OWID_WRL  1752               9354192
3    World  OWID_WRL  1753               9354192
4    World  OWID_WRL  1754               9357856
..     ...       ...   ...                   ...
267  World  OWID_WRL  2017           36096737000
268  World  OWID_WRL  2018           36826510000
269  World  OWID_WRL  2019           37082560000
270  World  OWID_WRL  2020           35264086000
271  World  OWID_WRL  2021           37123850000

[272 rows x 4 columns]

In [ ]:
df.head(5)

  Entity      Code  Year  Annual C02 emissions
0  World  OWID_WRL  1750               9350528
1  World  OWID_WRL  1751               9350528
2  World  OWID_WRL  1752               9354192
3  World  OWID_WRL  1753               9354192
4  World  OWID_WRL  1754               9357856

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,262,263,264,265,266,267,268,269,270,271
Entity,World,World,World,World,World,World,World,World,World,World,...,World,World,World,World,World,World,World,World,World,World
Code,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,...,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL,OWID_WRL
Year,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Annual C02 emissions,9350528,9350528,9354192,9354192,9357856,9361520,10006384,10010048,10013712,10017376,...,35006270000,35319200000,35577537000,35558568000,35524190000,36096737000,36826510000,37082560000,35264086000,37123850000

In [ ]:
df.T.to_dict

<bound method DataFrame.to_dict of                            0         1         2         3         4    \
Entity                   World     World     World     World     World
Code                  OWID_WRL  OWID_WRL  OWID_WRL  OWID_WRL  OWID_WRL
Year                      1750      1751      1752      1753      1754
Annual C02 emissions   9350528   9350528   9354192   9354192   9357856

                           5         6         7         8         9    ...  \
Entity                   World     World     World     World     World  ...
Code                  OWID_WRL  OWID_WRL  OWID_WRL  OWID_WRL  OWID_WRL  ...
Year                      1755      1756      1757      1758      1759  ...
Annual C02 emissions   9361520  10006384  10010048  10013712  10017376  ...

                              262          263          264          265  \
Entity                      World        World        World        World
Code                     OWID_WRL     OWID_WRL     OWID_WRL     OWID_WRL
Year                         2012         2013         2014         2015
Annual C02 emissions  35006270000  35319200000  35577537000  35558568000

                              266          267          268          269  \
Entity                      World        World        World        World
Code                     OWID_WRL     OWID_WRL     OWID_WRL     OWID_WRL
Year                         2016         2017         2018         2019
Annual C02 emissions  35524190000  36096737000  36826510000  37082560000

                              270          271
Entity                      World        World
Code                     OWID_WRL     OWID_WRL
Year                         2020         2021
Annual C02 emissions  35264086000  37123850000

[4 rows x 272 columns]>

In [ ]:
b.keys()

dict_keys(['alfa', 'beta', 'gamma', 'delta', 'ninety-eight'])

In [ ]:
list ( df.T.to_dict().values() )

[{'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1750,
  'Annual C02 emissions': 9350528},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1751,
  'Annual C02 emissions': 9350528},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1752,
  'Annual C02 emissions': 9354192},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1753,
  'Annual C02 emissions': 9354192},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1754,
  'Annual C02 emissions': 9357856},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1755,
  'Annual C02 emissions': 9361520},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1756,
  'Annual C02 emissions': 10006384},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1757,
  'Annual C02 emissions': 10010048},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1758,
  'Annual C02 emissions': 10013712},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1759,
  'Annual C02 emissions': 10017376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1760,
  'Annual C02 emissions': 10017376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1761,
  'Annual C02 emissions': 10973680},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1762,
  'Annual C02 emissions': 10977344},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1763,
  'Annual C02 emissions': 10981008},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1764,
  'Annual C02 emissions': 10984672},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1765,
  'Annual C02 emissions': 10988336},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1766,
  'Annual C02 emissions': 12259744},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1767,
  'Annual C02 emissions': 12263408},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1768,
  'Annual C02 emissions': 12267072},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1769,
  'Annual C02 emissions': 12270736},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1770,
  'Annual C02 emissions': 12274400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1771,
  'Annual C02 emissions': 13611760},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1772,
  'Annual C02 emissions': 13615424},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1773,
  'Annual C02 emissions': 13619088},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1774,
  'Annual C02 emissions': 13622752},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1775,
  'Annual C02 emissions': 13626416},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1776,
  'Annual C02 emissions': 15037056},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1777,
  'Annual C02 emissions': 15040720},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1778,
  'Annual C02 emissions': 15044384},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1779,
  'Annual C02 emissions': 15048048},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1780,
  'Annual C02 emissions': 15055376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1781,
  'Annual C02 emissions': 16843408},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1782,
  'Annual C02 emissions': 16847072},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1783,
  'Annual C02 emissions': 16854400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1784,
  'Annual C02 emissions': 16858064},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1785,
  'Annual C02 emissions': 16869056},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1786,
  'Annual C02 emissions': 19151728},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1787,
  'Annual C02 emissions': 19159056},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1788,
  'Annual C02 emissions': 19162720},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1789,
  'Annual C02 emissions': 19170048},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1790,
  'Annual C02 emissions': 19177376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1791,
  'Annual C02 emissions': 21419744},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1792,
  'Annual C02 emissions': 21896064},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1793,
  'Annual C02 emissions': 21914384},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1794,
  'Annual C02 emissions': 21881408},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1795,
  'Annual C02 emissions': 21892400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1796,
  'Annual C02 emissions': 22951296},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1797,
  'Annual C02 emissions': 24094464},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1798,
  'Annual C02 emissions': 25094736},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1799,
  'Annual C02 emissions': 26428432},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1800,
  'Annual C02 emissions': 28091888},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1801,
  'Annual C02 emissions': 27959984},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1802,
  'Annual C02 emissions': 36782896},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1803,
  'Annual C02 emissions': 31488416},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1804,
  'Annual C02 emissions': 34309696},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1805,
  'Annual C02 emissions': 33419346},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1806,
  'Annual C02 emissions': 35046160},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1807,
  'Annual C02 emissions': 36874496},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1808,
  'Annual C02 emissions': 35064480},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1809,
  'Annual C02 emissions': 35090130},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1810,
  'Annual C02 emissions': 37380130},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1811,
  'Annual C02 emissions': 39582190},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1812,
  'Annual C02 emissions': 41007490},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1813,
  'Annual C02 emissions': 41220000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1814,
  'Annual C02 emissions': 42128670},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1815,
  'Annual C02 emissions': 43488016},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1816,
  'Annual C02 emissions': 47664976},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1817,
  'Annual C02 emissions': 49431024},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1818,
  'Annual C02 emissions': 49643536},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1819,
  'Annual C02 emissions': 49947650},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1820,
  'Annual C02 emissions': 50687776},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1821,
  'Annual C02 emissions': 51435230},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1822,
  'Annual C02 emissions': 53465090},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1823,
  'Annual C02 emissions': 56550176},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1824,
  'Annual C02 emissions': 58525070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1825,
  'Annual C02 emissions': 60756450},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1826,
  'Annual C02 emissions': 61419630},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1827,
  'Annual C02 emissions': 65915360},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1828,
  'Annual C02 emissions': 66637170},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1829,
  'Annual C02 emissions': 66395348},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1830,
  'Annual C02 emissions': 89123140},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1831,
  'Annual C02 emissions': 84528480},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1832,
  'Annual C02 emissions': 85111060},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1833,
  'Annual C02 emissions': 86807490},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1834,
  'Annual C02 emissions': 88485600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1835,
  'Annual C02 emissions': 90445840},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1836,
  'Annual C02 emissions': 104775740},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1837,
  'Annual C02 emissions': 104691470},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1838,
  'Annual C02 emissions': 108044030},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1839,
  'Annual C02 emissions': 111612770},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1840,
  'Annual C02 emissions': 118929780},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1841,
  'Annual C02 emissions': 122619420},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1842,
  'Annual C02 emissions': 129504070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1843,
  'Annual C02 emissions': 132852984},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1844,
  'Annual C02 emissions': 141423070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1845,
  'Annual C02 emissions': 155210700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1846,
  'Annual C02 emissions': 157793820},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1847,
  'Annual C02 emissions': 172402190},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1848,
  'Annual C02 emissions': 173816500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1849,
  'Annual C02 emissions': 183511440},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1850,
  'Annual C02 emissions': 196896030},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1851,
  'Annual C02 emissions': 198804980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1852,
  'Annual C02 emissions': 207550940},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1853,
  'Annual C02 emissions': 217209250},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1854,
  'Annual C02 emissions': 255138980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1855,
  'Annual C02 emissions': 260165980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1856,
  'Annual C02 emissions': 277291520},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1857,
  'Annual C02 emissions': 279889280},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1858,
  'Annual C02 emissions': 284171300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1859,
  'Annual C02 emissions': 301311650},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1860,
  'Annual C02 emissions': 330641280},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1861,
  'Annual C02 emissions': 347734530},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1862,
  'Annual C02 emissions': 354056670},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1863,
  'Annual C02 emissions': 377859070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1864,
  'Annual C02 emissions': 407090300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1865,
  'Annual C02 emissions': 432306980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1866,
  'Annual C02 emissions': 445969700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1867,
  'Annual C02 emissions': 477814900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1868,
  'Annual C02 emissions': 490752500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1869,
  'Annual C02 emissions': 521130750},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1870,
  'Annual C02 emissions': 532536740},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1871,
  'Annual C02 emissions': 566143000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1872,
  'Annual C02 emissions': 626371800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1873,
  'Annual C02 emissions': 665419100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1874,
  'Annual C02 emissions': 622997250},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1875,
  'Annual C02 emissions': 675799100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1876,
  'Annual C02 emissions': 685552700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1877,
  'Annual C02 emissions': 699098500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1878,
  'Annual C02 emissions': 704379200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1879,
  'Annual C02 emissions': 754867200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1880,
  'Annual C02 emissions': 853704640},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1881,
  'Annual C02 emissions': 882405060},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1882,
  'Annual C02 emissions': 931921900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1883,
  'Annual C02 emissions': 991032400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1884,
  'Annual C02 emissions': 1002174300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1885,
  'Annual C02 emissions': 1009671360},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1886,
  'Annual C02 emissions': 1025475460},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1887,
  'Annual C02 emissions': 1076757800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1888,
  'Annual C02 emissions': 1192271900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1889,
  'Annual C02 emissions': 1191799600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1890,
  'Annual C02 emissions': 1298458200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1891,
  'Annual C02 emissions': 1358873900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1892,
  'Annual C02 emissions': 1370088300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1893,
  'Annual C02 emissions': 1353668700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1894,
  'Annual C02 emissions': 1400857700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1895,
  'Annual C02 emissions': 1485272600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1896,
  'Annual C02 emissions': 1533701400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1897,
  'Annual C02 emissions': 1606300500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1898,
  'Annual C02 emissions': 1694265700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1899,
  'Annual C02 emissions': 1850798100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1900,
  'Annual C02 emissions': 1952209500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1901,
  'Annual C02 emissions': 2016744400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1902,
  'Annual C02 emissions': 2067684100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1903,
  'Annual C02 emissions': 2254094800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1904,
  'Annual C02 emissions': 2279748900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1905,
  'Annual C02 emissions': 2427313200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1906,
  'Annual C02 emissions': 2534734300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1907,
  'Annual C02 emissions': 2888308000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1908,
  'Annual C02 emissions': 2776404200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1909,
  'Annual C02 emissions': 2890468000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1910,
  'Annual C02 emissions': 3033820000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1911,
  'Annual C02 emissions': 3079214800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1912,
  'Annual C02 emissions': 3235538400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1913,
  'Annual C02 emissions': 3505865200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1914,
  'Annual C02 emissions': 3179912400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1915,
  'Annual C02 emissions': 3134378200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1916,
  'Annual C02 emissions': 3385277400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1917,
  'Annual C02 emissions': 3539852500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1918,
  'Annual C02 emissions': 3492840000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1919,
  'Annual C02 emissions': 3028560000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1920,
  'Annual C02 emissions': 3521062400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1921,
  'Annual C02 emissions': 3089464300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1922,
  'Annual C02 emissions': 3239735800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1923,
  'Annual C02 emissions': 3675398000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1924,
  'Annual C02 emissions': 3686099200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1925,
  'Annual C02 emissions': 3725636600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1926,
  'Annual C02 emissions': 3659297000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1927,
  'Annual C02 emissions': 3993753900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1928,
  'Annual C02 emissions': 3976071200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1929,
  'Annual C02 emissions': 4267657200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1930,
  'Annual C02 emissions': 3934730000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1931,
  'Annual C02 emissions': 3516940500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1932,
  'Annual C02 emissions': 3170800600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1933,
  'Annual C02 emissions': 3338349300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1934,
  'Annual C02 emissions': 3630765300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1935,
  'Annual C02 emissions': 3811112000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1936,
  'Annual C02 emissions': 4181088300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1937,
  'Annual C02 emissions': 4469369300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1938,
  'Annual C02 emissions': 4201279700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1939,
  'Annual C02 emissions': 4445443000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1940,
  'Annual C02 emissions': 4854657500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1941,
  'Annual C02 emissions': 4965649000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1942,
  'Annual C02 emissions': 4953623600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1943,
  'Annual C02 emissions': 5035077000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1944,
  'Annual C02 emissions': 5110656000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1945,
  'Annual C02 emissions': 4250264000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1946,
  'Annual C02 emissions': 4638339000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1947,
  'Annual C02 emissions': 5138490000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1948,
  'Annual C02 emissions': 5415709700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1949,
  'Annual C02 emissions': 5245849000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1950,
  'Annual C02 emissions': 6003272000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1951,
  'Annual C02 emissions': 6379796500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1952,
  'Annual C02 emissions': 6465727000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1953,
  'Annual C02 emissions': 6647763000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1954,
  'Annual C02 emissions': 6789969000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1955,
  'Annual C02 emissions': 7443244000},
 {'Entity': 'World',

In [ ]:
exported_values = list( df.T.to_dict().values() )

In [ ]:
exported_values

[{'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1750,
  'Annual C02 emissions': 9350528},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1751,
  'Annual C02 emissions': 9350528},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1752,
  'Annual C02 emissions': 9354192},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1753,
  'Annual C02 emissions': 9354192},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1754,
  'Annual C02 emissions': 9357856},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1755,
  'Annual C02 emissions': 9361520},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1756,
  'Annual C02 emissions': 10006384},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1757,
  'Annual C02 emissions': 10010048},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1758,
  'Annual C02 emissions': 10013712},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1759,
  'Annual C02 emissions': 10017376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1760,
  'Annual C02 emissions': 10017376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1761,
  'Annual C02 emissions': 10973680},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1762,
  'Annual C02 emissions': 10977344},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1763,
  'Annual C02 emissions': 10981008},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1764,
  'Annual C02 emissions': 10984672},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1765,
  'Annual C02 emissions': 10988336},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1766,
  'Annual C02 emissions': 12259744},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1767,
  'Annual C02 emissions': 12263408},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1768,
  'Annual C02 emissions': 12267072},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1769,
  'Annual C02 emissions': 12270736},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1770,
  'Annual C02 emissions': 12274400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1771,
  'Annual C02 emissions': 13611760},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1772,
  'Annual C02 emissions': 13615424},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1773,
  'Annual C02 emissions': 13619088},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1774,
  'Annual C02 emissions': 13622752},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1775,
  'Annual C02 emissions': 13626416},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1776,
  'Annual C02 emissions': 15037056},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1777,
  'Annual C02 emissions': 15040720},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1778,
  'Annual C02 emissions': 15044384},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1779,
  'Annual C02 emissions': 15048048},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1780,
  'Annual C02 emissions': 15055376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1781,
  'Annual C02 emissions': 16843408},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1782,
  'Annual C02 emissions': 16847072},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1783,
  'Annual C02 emissions': 16854400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1784,
  'Annual C02 emissions': 16858064},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1785,
  'Annual C02 emissions': 16869056},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1786,
  'Annual C02 emissions': 19151728},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1787,
  'Annual C02 emissions': 19159056},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1788,
  'Annual C02 emissions': 19162720},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1789,
  'Annual C02 emissions': 19170048},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1790,
  'Annual C02 emissions': 19177376},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1791,
  'Annual C02 emissions': 21419744},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1792,
  'Annual C02 emissions': 21896064},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1793,
  'Annual C02 emissions': 21914384},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1794,
  'Annual C02 emissions': 21881408},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1795,
  'Annual C02 emissions': 21892400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1796,
  'Annual C02 emissions': 22951296},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1797,
  'Annual C02 emissions': 24094464},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1798,
  'Annual C02 emissions': 25094736},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1799,
  'Annual C02 emissions': 26428432},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1800,
  'Annual C02 emissions': 28091888},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1801,
  'Annual C02 emissions': 27959984},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1802,
  'Annual C02 emissions': 36782896},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1803,
  'Annual C02 emissions': 31488416},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1804,
  'Annual C02 emissions': 34309696},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1805,
  'Annual C02 emissions': 33419346},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1806,
  'Annual C02 emissions': 35046160},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1807,
  'Annual C02 emissions': 36874496},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1808,
  'Annual C02 emissions': 35064480},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1809,
  'Annual C02 emissions': 35090130},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1810,
  'Annual C02 emissions': 37380130},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1811,
  'Annual C02 emissions': 39582190},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1812,
  'Annual C02 emissions': 41007490},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1813,
  'Annual C02 emissions': 41220000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1814,
  'Annual C02 emissions': 42128670},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1815,
  'Annual C02 emissions': 43488016},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1816,
  'Annual C02 emissions': 47664976},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1817,
  'Annual C02 emissions': 49431024},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1818,
  'Annual C02 emissions': 49643536},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1819,
  'Annual C02 emissions': 49947650},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1820,
  'Annual C02 emissions': 50687776},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1821,
  'Annual C02 emissions': 51435230},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1822,
  'Annual C02 emissions': 53465090},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1823,
  'Annual C02 emissions': 56550176},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1824,
  'Annual C02 emissions': 58525070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1825,
  'Annual C02 emissions': 60756450},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1826,
  'Annual C02 emissions': 61419630},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1827,
  'Annual C02 emissions': 65915360},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1828,
  'Annual C02 emissions': 66637170},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1829,
  'Annual C02 emissions': 66395348},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1830,
  'Annual C02 emissions': 89123140},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1831,
  'Annual C02 emissions': 84528480},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1832,
  'Annual C02 emissions': 85111060},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1833,
  'Annual C02 emissions': 86807490},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1834,
  'Annual C02 emissions': 88485600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1835,
  'Annual C02 emissions': 90445840},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1836,
  'Annual C02 emissions': 104775740},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1837,
  'Annual C02 emissions': 104691470},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1838,
  'Annual C02 emissions': 108044030},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1839,
  'Annual C02 emissions': 111612770},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1840,
  'Annual C02 emissions': 118929780},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1841,
  'Annual C02 emissions': 122619420},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1842,
  'Annual C02 emissions': 129504070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1843,
  'Annual C02 emissions': 132852984},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1844,
  'Annual C02 emissions': 141423070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1845,
  'Annual C02 emissions': 155210700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1846,
  'Annual C02 emissions': 157793820},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1847,
  'Annual C02 emissions': 172402190},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1848,
  'Annual C02 emissions': 173816500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1849,
  'Annual C02 emissions': 183511440},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1850,
  'Annual C02 emissions': 196896030},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1851,
  'Annual C02 emissions': 198804980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1852,
  'Annual C02 emissions': 207550940},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1853,
  'Annual C02 emissions': 217209250},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1854,
  'Annual C02 emissions': 255138980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1855,
  'Annual C02 emissions': 260165980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1856,
  'Annual C02 emissions': 277291520},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1857,
  'Annual C02 emissions': 279889280},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1858,
  'Annual C02 emissions': 284171300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1859,
  'Annual C02 emissions': 301311650},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1860,
  'Annual C02 emissions': 330641280},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1861,
  'Annual C02 emissions': 347734530},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1862,
  'Annual C02 emissions': 354056670},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1863,
  'Annual C02 emissions': 377859070},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1864,
  'Annual C02 emissions': 407090300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1865,
  'Annual C02 emissions': 432306980},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1866,
  'Annual C02 emissions': 445969700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1867,
  'Annual C02 emissions': 477814900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1868,
  'Annual C02 emissions': 490752500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1869,
  'Annual C02 emissions': 521130750},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1870,
  'Annual C02 emissions': 532536740},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1871,
  'Annual C02 emissions': 566143000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1872,
  'Annual C02 emissions': 626371800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1873,
  'Annual C02 emissions': 665419100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1874,
  'Annual C02 emissions': 622997250},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1875,
  'Annual C02 emissions': 675799100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1876,
  'Annual C02 emissions': 685552700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1877,
  'Annual C02 emissions': 699098500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1878,
  'Annual C02 emissions': 704379200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1879,
  'Annual C02 emissions': 754867200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1880,
  'Annual C02 emissions': 853704640},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1881,
  'Annual C02 emissions': 882405060},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1882,
  'Annual C02 emissions': 931921900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1883,
  'Annual C02 emissions': 991032400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1884,
  'Annual C02 emissions': 1002174300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1885,
  'Annual C02 emissions': 1009671360},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1886,
  'Annual C02 emissions': 1025475460},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1887,
  'Annual C02 emissions': 1076757800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1888,
  'Annual C02 emissions': 1192271900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1889,
  'Annual C02 emissions': 1191799600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1890,
  'Annual C02 emissions': 1298458200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1891,
  'Annual C02 emissions': 1358873900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1892,
  'Annual C02 emissions': 1370088300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1893,
  'Annual C02 emissions': 1353668700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1894,
  'Annual C02 emissions': 1400857700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1895,
  'Annual C02 emissions': 1485272600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1896,
  'Annual C02 emissions': 1533701400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1897,
  'Annual C02 emissions': 1606300500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1898,
  'Annual C02 emissions': 1694265700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1899,
  'Annual C02 emissions': 1850798100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1900,
  'Annual C02 emissions': 1952209500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1901,
  'Annual C02 emissions': 2016744400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1902,
  'Annual C02 emissions': 2067684100},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1903,
  'Annual C02 emissions': 2254094800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1904,
  'Annual C02 emissions': 2279748900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1905,
  'Annual C02 emissions': 2427313200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1906,
  'Annual C02 emissions': 2534734300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1907,
  'Annual C02 emissions': 2888308000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1908,
  'Annual C02 emissions': 2776404200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1909,
  'Annual C02 emissions': 2890468000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1910,
  'Annual C02 emissions': 3033820000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1911,
  'Annual C02 emissions': 3079214800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1912,
  'Annual C02 emissions': 3235538400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1913,
  'Annual C02 emissions': 3505865200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1914,
  'Annual C02 emissions': 3179912400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1915,
  'Annual C02 emissions': 3134378200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1916,
  'Annual C02 emissions': 3385277400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1917,
  'Annual C02 emissions': 3539852500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1918,
  'Annual C02 emissions': 3492840000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1919,
  'Annual C02 emissions': 3028560000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1920,
  'Annual C02 emissions': 3521062400},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1921,
  'Annual C02 emissions': 3089464300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1922,
  'Annual C02 emissions': 3239735800},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1923,
  'Annual C02 emissions': 3675398000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1924,
  'Annual C02 emissions': 3686099200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1925,
  'Annual C02 emissions': 3725636600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1926,
  'Annual C02 emissions': 3659297000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1927,
  'Annual C02 emissions': 3993753900},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1928,
  'Annual C02 emissions': 3976071200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1929,
  'Annual C02 emissions': 4267657200},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1930,
  'Annual C02 emissions': 3934730000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1931,
  'Annual C02 emissions': 3516940500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1932,
  'Annual C02 emissions': 3170800600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1933,
  'Annual C02 emissions': 3338349300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1934,
  'Annual C02 emissions': 3630765300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1935,
  'Annual C02 emissions': 3811112000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1936,
  'Annual C02 emissions': 4181088300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1937,
  'Annual C02 emissions': 4469369300},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1938,
  'Annual C02 emissions': 4201279700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1939,
  'Annual C02 emissions': 4445443000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1940,
  'Annual C02 emissions': 4854657500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1941,
  'Annual C02 emissions': 4965649000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1942,
  'Annual C02 emissions': 4953623600},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1943,
  'Annual C02 emissions': 5035077000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1944,
  'Annual C02 emissions': 5110656000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1945,
  'Annual C02 emissions': 4250264000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1946,
  'Annual C02 emissions': 4638339000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1947,
  'Annual C02 emissions': 5138490000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1948,
  'Annual C02 emissions': 5415709700},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1949,
  'Annual C02 emissions': 5245849000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1950,
  'Annual C02 emissions': 6003272000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1951,
  'Annual C02 emissions': 6379796500},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1952,
  'Annual C02 emissions': 6465727000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1953,
  'Annual C02 emissions': 6647763000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1954,
  'Annual C02 emissions': 6789969000},
 {'Entity': 'World',
  'Code': 'OWID_WRL',
  'Year': 1955,
  'Annual C02 emissions': 7443244000},
 {'Entity': 'World',

In [ ]:
import json

In [ ]:
# json.dumps(exported_values)

In [ ]:
open('worldem_json.json', 'w').write( json.dumps(exported_values) )

24585